# Generated by Django 2.0.3 on 2018-07-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
