# Generated by Django 2.0.3 on 2018-07-21 04:01

from django.db import migrations, models
import nextbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook', '0002_auto_20180703_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.IntegerField(default=nextbook.models.Book.lib_total, unique=True),
        ),
    ]
